use Pokemon;
SELECT name FROM Trainer WHERE Trainer.hometown = "Blue City";
SELECT name FROM Trainer WHERE Trainer.hometown = "Brown City" OR Trainer.hometown = "Rainbow City";
SELECT name, hometown FROM Trainer AS T WHERE T.name LIKE 'A%' or T.name LIKE 'E%' or T.name LIKE 'I%' or T.name LIKE "O%" or T.name LIKE "U%";
SELECT name FROM Pokemon WHERE Pokemon.type = "Water";
SELECT DISTINCT type FROM Pokemon;
SELECT name FROM Pokemon ORDER BY name;
SELECT name FROM Pokemon AS P WHERE P.name LIKE '%S';
SELECT name FROM Pokemon AS P WHERE P.name LIKE '%E%S';
SELECT name FROM Pokemon AS P WHERE P.name LIKE 'A%' OR P.name LIKE 'E%' OR P.name LIKE 'I%' OR P.name LIKE 'O%' OR P.name LIKE 'U%';
SELECT type, COUNT(*) FROM Pokemon GROUP BY type;
SELECT nickname FROM CatchedPokemon ORDER BY -level LIMIT 3;
SELECT AVG(level) FROM CatchedPokemon;
SELECT MAX(level)-MIN(level) FROM CatchedPokemon;
SELECT COUNT(*) FROM Pokemon AS P WHERE P.name BETWEEN 'B%' AND 'F%';
SELECT COUNT(*) FROM Pokemon AS P WHERE P.type != "Fire" AND P.type != "Grass" AND P.type != "Water" AND P.type != "Electric";
SELECT T.name, P.name, C.nickname FROM Trainer AS T, Pokemon P, CatchedPokemon AS C WHERE C.nickname LIKE '% %' AND T.id = C.owner_id AND P.id = C.pid;
SELECT T.name FROM Trainer AS T, Pokemon AS P, CatchedPokemon AS C WHERE C.pid = P.id AND P.type = "Psychic" AND T.id = C.owner_id;
SELECT T.name, T.hometown  FROM Trainer T, CatchedPokemon AS C WHERE T.id = C.owner_id GROUP BY C.owner_id ORDER BY -AVG(level) LIMIT 3;
SELECT T.name, COUNT(*) FROM Trainer AS T, CatchedPokemon AS C WHERE T.id = C.owner_id GROUP BY C.owner_id ORDER BY -COUNT(*), T.name DESC;
SELECT P.name, C.level FROM Pokemon AS P, CatchedPokemon AS C WHERE P.id = C.pid AND C.owner_id = ( SELECT T.id FROM Trainer AS T, Gym AS G WHERE G.city = "Sangnok City" AND T.id = G.leader_id ) ORDER BY C.level;
SELECT P.name, COUNT(C.pid) FROM Pokemon AS P LEFT JOIN CatchedPokemon AS C ON P.id = C.pid GROUP BY P.id ORDER BY -COUNT(C.pid);
SELECT P.name FROM Pokemon AS P, Evolution AS E WHERE P.id = E.after_id AND E.before_id = (SELECT E.after_id FROM Pokemon AS P, Evolution AS E WHERE P.name = "Charmander" AND E.before_id = P.id);
SELECT P.name  FROM Pokemon AS P, CatchedPokemon AS C WHERE P.id = C.pid AND P.id <= 30 GROUP BY P.name ORDER BY P.name;
SELECT T.name, P.type FROM Trainer AS T, Pokemon AS P, CatchedPokemon AS C WHERE C.owner_id = T.id AND C.pid = P.id GROUP BY T.id HAVING COUNT(DISTINCT P.type) = 1;
SELECT T.name, P.type, count(*) FROM Trainer AS T, Pokemon AS P, CatchedPokemon AS C WHERE C.owner_id = T.id AND C.pid = P.id GROUP BY T.name, P.type ORDER BY T.id, P.type;
SELECT T.name, P.name, count(*) FROM Trainer AS T, Pokemon AS P, CatchedPokemon AS C WHERE T.id = C.owner_id AND P.id = C.pid GROUP BY T.name HAVING AVG(P.id) = MAX(P.id);
SELECT T.name, T.hometown FROM Trainer AS T, Gym AS G, CatchedPokemon C, Pokemon AS P WHERE T.id = G.leader_id AND C.owner_id = T.id AND P.id = C.pid GROUP BY G.leader_id HAVING COUNT(DISTINCT P.type) != 1;
SELECT T.name, SUM(C.level) FROM Trainer AS T LEFT JOIN CatchedPokemon AS C ON T.id = C.owner_id AND C.level >= 50 RIGHT JOIN Gym AS G ON T.id = G.leader_id GROUP BY G.leader_id;
SELECT name FROM Pokemon WHERE id IN ( SELECT pid FROM CatchedPokemon AS C, Trainer AS T WHERE C.owner_id = T.id AND T.hometown = "Sangnok City") AND id IN ( SELECT pid FROM CatchedPokemon AS C, Trainer AS T WHERE C.owner_id = T.id AND T.hometown = "Blue City");
SELECT DISTINCT P.name FROM Pokemon AS P, Evolution AS E WHERE P.id = E.after_id AND NOT EXISTS (SELECT * FROM Evolution AS E WHERE P.id = E.before_id);
